/* ========================================
   Catálogo de Produtos - 120+ Modelos
   Fonte: MakerWorld (makerworld.com)
   ======================================== */

var PRODUTOS = [

  // ============================================================
  // MENINAS - Fofos & Decorativos
  // ============================================================

  // Animais Kawaii
  { id: 1, name: "Gatinho Kawaii Anime", category: "Animais Fofos", audience: "meninas", price: 27.00, production: "3-5 dias", colors: 12, badge: "Mais Vendido", popular: 95, image: "anime-kawaii-cat.jpg", icon: "fas fa-cat", gradient: "gradient-1", creator: "Czain", url: "https://makerworld.com/en/models/1024927-anime-kawaii-cute-cat", description: "Gatinho estilo anime chibi, perfeito para decorar mesa ou estante", tags: ["gato", "kawaii", "anime", "fofo", "decoração"] },
  { id: 2, name: "Coelhinho Kawaii Rechonchudo", category: "Animais Fofos", audience: "meninas", price: 22.50, production: "3-5 dias", colors: 15, badge: "Mais Vendido", popular: 90, image: "chubby-kawaii-rabbit.jpg", icon: "fas fa-rabbit", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/2080085-chubby-kawaii-rabbit-keychain-figurine", description: "Coelho rechonchudo kawaii, versão chaveiro e miniatura", tags: ["coelho", "kawaii", "fofo", "chaveiro"] },
  { id: 3, name: "Coelhinho Fofo Multicolor", category: "Animais Fofos", audience: "meninas", price: 30.00, production: "3-5 dias", colors: 10, badge: "", popular: 80, image: "cute-bunny.jpg", icon: "fas fa-rabbit", gradient: "gradient-3", creator: "3DPrintyi", url: "https://makerworld.com/en/models/1141244-cute-bunny", description: "Coelho multicolorido com detalhes em rosa e branco", tags: ["coelho", "fofo", "multicolor", "presente"] },
  { id: 4, name: "Coelho Articulado Flexi", category: "Animais Fofos", audience: "meninas", price: 33.00, production: "3-5 dias", colors: 15, badge: "Novo", popular: 75, image: "articulated-rabbit.jpg", icon: "fas fa-rabbit", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/models/2203095-articulated-rabbit-cute-flexi-bunny-toy", description: "Coelhinho articulado flexi, mexe todas as partes", tags: ["coelho", "articulado", "flexível", "brinquedo"] },

  // Flores & Decoração
  { id: 5, name: "Buquê de Tulipas", category: "Flores & Decoração", audience: "meninas", price: 45.00, production: "5-7 dias", colors: 8, badge: "Mais Vendido", popular: 92, image: "bouquet-tulips.jpg", icon: "fas fa-seedling", gradient: "gradient-5", creator: "MiMa3D", url: "https://makerworld.com/en/models/417257-bouquet-of-tulips", description: "Buquê de tulipas com vaso incluso, presente perfeito", tags: ["flor", "tulipa", "buquê", "presente", "decoração"] },
  { id: 6, name: "Rosa Decorativa", category: "Flores & Decoração", audience: "meninas", price: 18.00, production: "3-5 dias", colors: 10, badge: "", popular: 85, image: "rose-flower.jpg", icon: "fas fa-spa", gradient: "gradient-6", creator: "Ardent", url: "https://makerworld.com/en/models/988983-rose-flower", description: "Rosa com pétalas detalhadas, caule e sépala para montar", tags: ["rosa", "flor", "romântico", "presente"] },
  { id: 7, name: "Tulipa com Caule e Folhas", category: "Flores & Decoração", audience: "meninas", price: 15.00, production: "2-3 dias", colors: 12, badge: "", popular: 70, image: "tulip-stem.jpg", icon: "fas fa-leaf", gradient: "gradient-7", creator: "Bruce Wen Design", url: "https://makerworld.com/en/models/1331914-tulip-with-stem-and-leaves", description: "Tulipa realista com caule e folhas", tags: ["tulipa", "flor", "decoração"] },
  { id: 8, name: "Jardim de Tulipas e Jasmim", category: "Flores & Decoração", audience: "meninas", price: 60.00, production: "5-7 dias", colors: 8, badge: "Novo", popular: 78, image: "spring-yarn-garden.jpg", icon: "fas fa-tree", gradient: "gradient-8", creator: "花田小猫", url: "https://makerworld.com/en/models/1273557-spring-yarn-garden-tulips-and-jasmine-flowers", description: "Conjunto jardim com tulipas e jasmim estilo crochê", tags: ["jardim", "flores", "crochê", "decoração", "kit"] },
  { id: 9, name: "Tulipa Love com Coração", category: "Flores & Decoração", audience: "meninas", price: 18.00, production: "2-3 dias", colors: 10, badge: "", popular: 72, image: "flowers-tulip-love.jpg", icon: "fas fa-heart", gradient: "gradient-1", creator: "michal0082", url: "https://makerworld.com/en/models/167584-flowers-tulip", description: "Tulipa com base em coração escrito LOVE", tags: ["tulipa", "love", "coração", "presente", "romântico"] },

  // Fantasia & Princesas
  { id: 10, name: "Princesa Borboleta", category: "Fantasia & Princesas", audience: "meninas", price: 37.50, production: "5-7 dias", colors: 10, badge: "Mais Vendido", popular: 88, image: "butterfly-princess.jpg", icon: "fas fa-crown", gradient: "gradient-2", creator: "水星", url: "https://makerworld.com/en/models/1201241-butterfly-princess", description: "Princesa borboleta para colorir, crianças adoram", tags: ["princesa", "borboleta", "fantasia", "crianças"] },
  { id: 11, name: "Unicórnio Mágico", category: "Fantasia & Princesas", audience: "meninas", price: 42.00, production: "5-7 dias", colors: 8, badge: "", popular: 85, image: "unicorn.jpg", icon: "fas fa-horse", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/777378-unicorn", description: "Unicórnio detalhado com chifre e crina", tags: ["unicórnio", "fantasia", "mágico", "decoração"] },
  { id: 12, name: "Coroa de Unicórnio", category: "Fantasia & Princesas", audience: "meninas", price: 22.50, production: "3-5 dias", colors: 6, badge: "", popular: 65, image: "unicorn-crown.jpg", icon: "fas fa-crown", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/models/63904-unicorn-crown-with-horn-adornments", description: "Coroa de unicórnio vestível com chifre", tags: ["coroa", "unicórnio", "fantasia", "cosplay"] },
  { id: 14, name: "Coração Floral com Borboleta", category: "Flores & Decoração", audience: "meninas", price: 24.00, production: "3-5 dias", colors: 8, badge: "", popular: 75, image: "floral-heart-butterfly.jpg", icon: "fas fa-heart", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/models/213355-floral-heart-butterfly-decoration-cake-topper", description: "Coração com flores e borboleta, topo de bolo ou decoração de parede", tags: ["coração", "borboleta", "floral", "bolo", "decoração"] },

  // Organizadores & Vasos
  { id: 15, name: "Vaso Fluffy Fofinho", category: "Vasos & Plantas", audience: "meninas", price: 45.00, production: "3-5 dias", colors: 10, badge: "Mais Vendido", popular: 88, image: "fluffy-planter.jpg", icon: "fas fa-leaf", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/843030-fluffy-planter-vase", description: "Vaso fofinho estilo fluffy para plantas ou porta-lápis", tags: ["vaso", "planta", "fluffy", "fofo", "decoração"] },
  { id: 16, name: "Porta-Retrato Decorativo Redondo", category: "Porta-Retratos", audience: "meninas", price: 30.00, production: "3-5 dias", colors: 8, badge: "", popular: 70, image: "decorative-frame.jpg", icon: "fas fa-image", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/2103882-decorative-round-picture-mirror-frame", description: "Porta-retrato ou espelho estilo barroco redondo", tags: ["porta-retrato", "espelho", "decoração", "barroco"] },
  { id: 17, name: "Porta-Retrato de Mesa", category: "Porta-Retratos", audience: "meninas", price: 18.00, production: "2-3 dias", colors: 12, badge: "", popular: 65, image: "picture-frame-stand.jpg", icon: "fas fa-image", gradient: "gradient-1", creator: "sabergum", url: "https://makerworld.com/en/models/651625-picture-frame-stand", description: "Suporte de mesa para fotos e porta-retratos", tags: ["porta-retrato", "mesa", "foto"] },
  { id: 18, name: "Organizador Moderno Multiuso", category: "Organização", audience: "meninas", price: 52.50, production: "5-7 dias", colors: 10, badge: "", popular: 73, image: "long-modern-planter.jpg", icon: "fas fa-box", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/2028384-long-modern-planter-multi-purpose-organizer", description: "Organizador moderno para maquiagem, plantas ou acessórios", tags: ["organizador", "moderno", "maquiagem", "multiuso"] },

  // ============================================================
  // MENINOS - Ação & Aventura
  // ============================================================

  // Dragões & Dinossauros
  { id: 19, name: "Dragão Robô Articulado", category: "Dragões & Dinossauros", audience: "meninos", price: 67.50, production: "5-7 dias", colors: 10, badge: "Mais Vendido", popular: 96, image: "robot-dragon.jpg", icon: "fas fa-dragon", gradient: "gradient-3", creator: "Filionix3D", url: "https://makerworld.com/en/models/187368-robot-dragon-articulated-puzzle", description: "Dragão robô articulado, cada junta se move livremente", tags: ["dragão", "robô", "articulado", "puzzle"] },
  { id: 20, name: "Dragão Articulado Printesion", category: "Dragões & Dinossauros", audience: "meninos", price: 60.00, production: "5-7 dias", colors: 15, badge: "Mais Vendido", popular: 94, image: "articulated-dragon.jpg", icon: "fas fa-dragon", gradient: "gradient-4", creator: "Printesion", url: "https://makerworld.com/en/models/116169-articulated-dragon-printesion", description: "Dragão articulado clássico, print-in-place", tags: ["dragão", "articulado", "fantasia"] },
  { id: 21, name: "Dino-Robô Articulado T-Rex", category: "Dragões & Dinossauros", audience: "meninos", price: 52.50, production: "5-7 dias", colors: 10, badge: "", popular: 88, image: "dino-robot.jpg", icon: "fas fa-paw", gradient: "gradient-5", creator: "DT3D_PR1NT", url: "https://makerworld.com/en/models/1113500-dino-robot-articulated-toy", description: "T-Rex robô articulado, mistura dinossauro com mecânico", tags: ["dinossauro", "t-rex", "robô", "articulado"] },

  // Veículos & Foguetes
  { id: 22, name: "Tanque Lançador de Foguetes", category: "Veículos & Foguetes", audience: "meninos", price: 75.00, production: "5-7 dias", colors: 6, badge: "", popular: 82, image: "rocket-launcher-tank.jpg", icon: "fas fa-rocket", gradient: "gradient-6", creator: "Kit Crafters", url: "https://makerworld.com/en/models/711290-rocket-launcher-tank-model-kit", description: "Tanque militar com lançador de foguetes duplo", tags: ["tanque", "militar", "foguete", "modelo"] },
  { id: 23, name: "Foguete Espacial Helix Fidget", category: "Veículos & Foguetes", audience: "meninos", price: 27.00, production: "3-5 dias", colors: 12, badge: "Mais Vendido", popular: 90, image: "helix-rocket.jpg", icon: "fas fa-rocket", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/526796", description: "Foguete que gira como spinner, fidget vortex", tags: ["foguete", "spinner", "fidget", "espaço"] },
  { id: 24, name: "Foguete Minimalista", category: "Veículos & Foguetes", audience: "meninos", price: 22.50, production: "3-5 dias", colors: 10, badge: "", popular: 75, image: "minimalist-rocket.jpg", icon: "fas fa-rocket", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/542585-minimalist-rocket-ship", description: "Foguete design minimalista para decorar mesa", tags: ["foguete", "minimalista", "decoração", "mesa"] },
  { id: 25, name: "Nave Starship Sci-Fi NASA", category: "Veículos & Foguetes", audience: "meninos", price: 82.50, production: "7-10 dias", colors: 6, badge: "Novo", popular: 80, image: "nasa-starship.jpg", icon: "fas fa-shuttle-space", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/models/2390296-sci-fi-nasa-starship", description: "Nave Starship da NASA em versão sci-fi", tags: ["nave", "NASA", "sci-fi", "espaço"] },
  { id: 26, name: "Tanque Carrier Kit", category: "Veículos & Foguetes", audience: "meninos", price: 72.00, production: "5-7 dias", colors: 6, badge: "", popular: 78, image: "carrier-tank.jpg", icon: "fas fa-truck-monster", gradient: "gradient-2", creator: "Kit Crafters", url: "https://makerworld.com/en/models/713803-carrier-tank-model-kit", description: "Tanque carrier com lançador de mísseis duplos", tags: ["tanque", "militar", "kit", "modelo"] },

  // Espadas & Armas Cosplay
  { id: 27, name: "Espada do Rei Esquecido", category: "Espadas & Cosplay", audience: "meninos", price: 97.50, production: "7-10 dias", colors: 4, badge: "Mais Vendido", popular: 91, image: "forgotten-king-sword.jpg", icon: "fas fa-gavel", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/1944121-blade-of-the-forgotten-king-fantasy-cosplay-sword", description: "Espada fantasia tamanho real para cosplay ou decoração", tags: ["espada", "cosplay", "fantasia", "decoração"] },
  { id: 28, name: "Espada Darksteel", category: "Espadas & Cosplay", audience: "meninos", price: 87.00, production: "7-10 dias", colors: 4, badge: "", popular: 85, image: "darksteel-sword.jpg", icon: "fas fa-gavel", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/models/2501373-the-darksteel-sword-cosplay-prop", description: "Espada dark fantasy, design elegante e sombrio", tags: ["espada", "dark", "cosplay", "fantasy"] },
  { id: 29, name: "Link com Espada e Escudo", category: "Espadas & Cosplay", audience: "meninos", price: 57.00, production: "5-7 dias", colors: 8, badge: "Novo", popular: 87, image: "link-zelda.jpg", icon: "fas fa-shield-halved", gradient: "gradient-5", creator: "MakerWorld", url: "https://makerworld.com/en/models/1124284-link-with-sword-and-shield", description: "Link do Zelda com espada e escudo, miniatura colecionável", tags: ["zelda", "link", "espada", "escudo", "nintendo"] },
  { id: 30, name: "Guerreira Amazona com Machado", category: "Espadas & Cosplay", audience: "meninos", price: 63.00, production: "5-7 dias", colors: 6, badge: "", popular: 72, image: "amazon-warrior.jpg", icon: "fas fa-shield-halved", gradient: "gradient-6", creator: "T&T Production", url: "https://makerworld.com/en/models/1501757-amazon-warrior-with-axe-and-shield", description: "Guerreira amazona com machado e escudo detalhados", tags: ["guerreira", "machado", "escudo", "fantasia"] },

  // Caveiras & Halloween
  { id: 31, name: "Esqueleto Articulado Halloween", category: "Caveiras & Halloween", audience: "meninos", price: 52.50, production: "5-7 dias", colors: 6, badge: "Mais Vendido", popular: 92, image: "articulated-skeleton.jpg", icon: "fas fa-skull", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/729130-articulated-skeleton", description: "Esqueleto humano articulado completo, flexível", tags: ["esqueleto", "halloween", "articulado"] },
  { id: 32, name: "Caveira com Coluna Articulada", category: "Caveiras & Halloween", audience: "meninos", price: 45.00, production: "5-7 dias", colors: 6, badge: "", popular: 85, image: "spine-skull.jpg", icon: "fas fa-skull-crossbones", gradient: "gradient-8", creator: "Bofonchio", url: "https://makerworld.com/en/models/691363-articulated-halloween-spine-and-skull", description: "Caveira com coluna vertebral articulada", tags: ["caveira", "coluna", "halloween", "articulado"] },
  { id: 33, name: "Esqueleto Flexi Halloween", category: "Caveiras & Halloween", audience: "meninos", price: 33.00, production: "3-5 dias", colors: 8, badge: "", popular: 80, image: "skeleton-flexy.jpg", icon: "fas fa-bone", gradient: "gradient-1", creator: "Printpals", url: "https://makerworld.com/en/models/1779144-articulated-skeleton-halloween-flexy", description: "Esqueleto flexível e engraçado para mesa", tags: ["esqueleto", "flexi", "halloween", "mesa"] },
  { id: 34, name: "Caveira Anatômica Realista", category: "Caveiras & Halloween", audience: "meninos", price: 63.00, production: "5-7 dias", colors: 4, badge: "", popular: 77, image: "anatomical-skull.jpg", icon: "fas fa-skull", gradient: "gradient-2", creator: "3Demon", url: "https://makerworld.com/en/models/200604-anatomically-correct-human-skull-by-3demon", description: "Caveira anatomicamente correta, réplica realista", tags: ["caveira", "anatomia", "realista", "ciência"] },
  { id: 35, name: "Esqueleto Minecraft Articulado", category: "Gaming & Geek", audience: "meninos", price: 33.00, production: "3-5 dias", colors: 6, badge: "Novo", popular: 83, image: "minecraft-skeleton.jpg", icon: "fas fa-gamepad", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/820195-minecraft-skeleton-print-in-place-articulated", description: "Esqueleto do Minecraft articulado print-in-place", tags: ["minecraft", "esqueleto", "gaming", "articulado"] },
  { id: 36, name: "Caveira Articulada Mandíbula", category: "Caveiras & Halloween", audience: "meninos", price: 30.00, production: "3-5 dias", colors: 8, badge: "", popular: 78, image: "articulated-skull.jpg", icon: "fas fa-skull", gradient: "gradient-4", creator: "GreyCanadianWizard", url: "https://makerworld.com/en/models/158101-articulated-skull", description: "Caveira com mandíbula articulada que abre e fecha", tags: ["caveira", "mandíbula", "articulado"] },

  // Gaming & Geek
  { id: 37, name: "Pikachu Pokémon", category: "Gaming & Geek", audience: "meninos", price: 27.00, production: "3-5 dias", colors: 8, badge: "Mais Vendido", popular: 95, image: "pikachu.jpg", icon: "fas fa-bolt", gradient: "gradient-5", creator: "SnapPrint3D", url: "https://makerworld.com/en/models/50835-pokemon-pikachu-no-support", description: "Pikachu clássico sem suporte, fácil de imprimir", tags: ["pikachu", "pokémon", "gaming", "anime"] },
  { id: 38, name: "Figura Roblox Articulada", category: "Gaming & Geek", audience: "meninos", price: 24.00, production: "3-5 dias", colors: 10, badge: "", popular: 82, image: "roblox-figure.jpg", icon: "fas fa-user", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/models/652148-articulated-roblox-figure", description: "Personagem Roblox articulado clássico", tags: ["roblox", "gaming", "articulado", "figura"] },
  { id: 39, name: "Among Us Crewmate Realista", category: "Gaming & Geek", audience: "meninos", price: 21.00, production: "3-5 dias", colors: 12, badge: "", popular: 80, image: "among-us.jpg", icon: "fas fa-user-astronaut", gradient: "gradient-7", creator: "John Galt", url: "https://makerworld.com/en/models/702734", description: "Crewmate do Among Us versão realista detalhada", tags: ["among us", "gaming", "astronauta"] },

  // ============================================================
  // UNISSEX - Organização, Setup & Utilidades
  // ============================================================

  // Fidgets & Chaveiros (já existentes + novos)
  { id: 40, name: "Chaveiro Fidget Engrenagem", category: "Fidgets & Chaveiros", audience: "unissex", price: 22.50, production: "3-5 dias", colors: 12, badge: "Mais Vendido", popular: 95, image: "gear-click-fidget.jpg", icon: "fas fa-hand-pointer", gradient: "gradient-1", creator: "Eternity Labs", url: "https://makerworld.com/en/models/556148-gear-click-fidget-keychain-print-in-place", description: "Fidget de engrenagem que clica satisfatoriamente", tags: ["fidget", "chaveiro", "engrenagem", "clicker"] },
  { id: 42, name: "Ervilha Fidget Anti-Stress", category: "Fidgets & Chaveiros", audience: "unissex", price: 15.00, production: "3-5 dias", colors: 15, badge: "", popular: 85, image: "peapod-clicker.jpg", icon: "fas fa-hand-pointer", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/1492580-peapod-clicker-fidget-keychain-toy", description: "Ervilha clicker anti-stress fofa e compacta", tags: ["fidget", "clicker", "ervilha", "fofo"] },
  { id: 43, name: "Chaveiro Motor Rotativo Miniatura", category: "Fidgets & Chaveiros", audience: "unissex", price: 24.00, production: "3-5 dias", colors: 10, badge: "Novo", popular: 80, image: "rotary-engine-fidget.jpg", icon: "fas fa-cog", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/models/675091-rotary-engine-keychain-fidget-print-in-place", description: "Motor rotativo miniatura que gira de verdade", tags: ["motor", "rotativo", "chaveiro", "engenharia"] },
  { id: 44, name: "Chaveiro Coração Giratório", category: "Fidgets & Chaveiros", audience: "unissex", price: 18.00, production: "3-5 dias", colors: 12, badge: "", popular: 78, image: "heart-spin-fidget.jpg", icon: "fas fa-heart", gradient: "gradient-5", creator: "MakerWorld", url: "https://makerworld.com/en/models/2280290-heart-spin-keychain-fidget", description: "Coração com disco giratório interno anti-stress", tags: ["coração", "fidget", "giratório", "presente"] },

  // Suportes & Organização
  { id: 45, name: "Suporte para Celular Industrial", category: "Suportes & Setup", audience: "unissex", price: 42.00, production: "3-5 dias", colors: 8, badge: "Mais Vendido", popular: 93, image: "phone-stand-industrial.jpg", icon: "fas fa-mobile-alt", gradient: "gradient-6", creator: "Josh-3D", url: "https://makerworld.com/en/models/202649-phone-stand-industrial", description: "Suporte robusto estilo industrial para celular", tags: ["suporte", "celular", "industrial", "mesa"] },
  { id: 46, name: "Organizador Modular de Mesa", category: "Organização", audience: "unissex", price: 67.50, production: "5-7 dias", colors: 10, badge: "Mais Vendido", popular: 90, image: "modular-desk-organiser.jpg", icon: "fas fa-pen-ruler", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/609121-modular-desk-organiser", description: "Organizador modular com compartimentos configuráveis", tags: ["organizador", "modular", "mesa", "escritório"] },
  { id: 47, name: "Poly-Desk Organizador", category: "Organização", audience: "unissex", price: 75.00, production: "5-7 dias", colors: 15, badge: "", popular: 85, image: "poly-desk-organizer.jpg", icon: "fas fa-th-large", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/1820511-poly-desk-organizer", description: "Organizador com slots para canetas, SD, USB e gaveta", tags: ["organizador", "poly", "canetas", "USB", "SD"] },
  { id: 48, name: "Organizador de Cabos Portátil", category: "Organização", audience: "unissex", price: 18.00, production: "2-3 dias", colors: 15, badge: "", popular: 88, image: "cable-organizer.jpg", icon: "fas fa-plug", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/models/13849-portable-cable-organizer-winder", description: "Enrolador de cabos portátil com knob lateral, 86K downloads", tags: ["cabo", "organizador", "portátil", "USB"] },
  { id: 49, name: "Porta-Canetas 5 Anéis", category: "Organização", audience: "unissex", price: 45.00, production: "3-5 dias", colors: 10, badge: "Novo", popular: 75, image: "pen-holder-olympic.jpg", icon: "fas fa-pen", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/920556-5-ring-olympic-quality-desk-organizer-pen-holder", description: "Porta-canetas estilo olímpico com 5 anéis e 2 alturas", tags: ["canetas", "porta-canetas", "olímpico", "mesa"] },
  { id: 50, name: "Organizador Escalonado", category: "Organização", audience: "unissex", price: 60.00, production: "5-7 dias", colors: 15, badge: "", popular: 73, image: "stepped-desk-organizer.jpg", icon: "fas fa-layer-group", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/710122-stepped-desk-organizer", description: "Organizador em degraus com insertos modulares", tags: ["organizador", "escalonado", "modular", "mesa"] },

  // Suportes Gaming
  { id: 51, name: "Suporte para Controle Gamer", category: "Suportes & Setup", audience: "unissex", price: 48.00, production: "3-5 dias", colors: 8, badge: "Mais Vendido", popular: 91, image: "controller-stand.jpg", icon: "fas fa-gamepad", gradient: "gradient-4", creator: "Coeus3D", url: "https://makerworld.com/en/models/252915-game-controller-display-stand", description: "Suporte elegante para 1-2 controles de qualquer console", tags: ["controle", "gamer", "suporte", "display"] },
  { id: 52, name: "Suporte para Headphone Design", category: "Suportes & Setup", audience: "unissex", price: 72.00, production: "5-7 dias", colors: 8, badge: "", popular: 85, image: "design-headphone-stand.jpg", icon: "fas fa-headphones", gradient: "gradient-5", creator: "Deltaprints", url: "https://makerworld.com/en/models/515356-design-headphone-stand", description: "Suporte headphone design moderno e minimalista", tags: ["headphone", "fone", "suporte", "design"] },
  { id: 53, name: "Suporte Headphone Moderno", category: "Suportes & Setup", audience: "unissex", price: 63.00, production: "5-7 dias", colors: 6, badge: "", popular: 82, image: "headphone-holder-modern.jpg", icon: "fas fa-headphones", gradient: "gradient-6", creator: "ngprint", url: "https://makerworld.com/en/models/231863-headphone-holder-modern-design", description: "Headphone holder com parafuso ajustável e giro universal", tags: ["headphone", "fone", "moderno", "ajustável"] },
  { id: 54, name: "Suporte Gamer Futurista", category: "Suportes & Setup", audience: "unissex", price: 97.50, production: "7-10 dias", colors: 6, badge: "Novo", popular: 80, image: "futuristic-gaming-stand.jpg", icon: "fas fa-gamepad", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/1048970-futuristic-gaming-headset-controller-stand", description: "Suporte futurista hexagonal para headset e controle", tags: ["gamer", "futurista", "headset", "controle"] },
  { id: 55, name: "Suporte Controle Xbox Sob Mesa", category: "Suportes & Setup", audience: "unissex", price: 33.00, production: "3-5 dias", colors: 8, badge: "", popular: 78, image: "xbox-under-desk.jpg", icon: "fas fa-gamepad", gradient: "gradient-8", creator: "Lucas Weug", url: "https://makerworld.com/en/models/739888-xbox-controller-holder-under-desk", description: "Holder para controle Xbox sob a mesa, escondido e organizado", tags: ["xbox", "controle", "mesa", "hidden"] },

  // Porta-Copos & Utilitários
  { id: 59, name: "Porta-Copos Relief + Caixa", category: "Casa & Utilidades", audience: "unissex", price: 52.50, production: "5-7 dias", colors: 8, badge: "Mais Vendido", popular: 86, image: "relief-coasters.jpg", icon: "fas fa-glass-whiskey", gradient: "gradient-4", creator: "HpInvent", url: "https://makerworld.com/en/models/535553-relief-coaster-collection-storage-box", description: "Coleção de porta-copos com texturas + caixa organizadora", tags: ["porta-copos", "coaster", "caixa", "casa"] },
  { id: 60, name: "Porta-Copos Nostalgia Gamer", category: "Casa & Utilidades", audience: "unissex", price: 57.00, production: "5-7 dias", colors: 6, badge: "Novo", popular: 84, image: "nostalgia-coasters.jpg", icon: "fas fa-gamepad", gradient: "gradient-5", creator: "HpInvent", url: "https://makerworld.com/en/models/1512405-nostalgia-drink-coaster-storage-box", description: "Porta-copos formato cartucho com caixa console retrô", tags: ["porta-copos", "gamer", "nostalgia", "retrô"] },
  { id: 61, name: "Suporte Porta-Copos Quadrado", category: "Casa & Utilidades", audience: "unissex", price: 22.50, production: "2-3 dias", colors: 10, badge: "", popular: 68, image: "square-coaster-holder.jpg", icon: "fas fa-square", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/models/997182-square-coaster-holder", description: "Suporte organizador para porta-copos quadrados", tags: ["porta-copos", "suporte", "casa"] },
  { id: 62, name: "Suporte para Bookmarks", category: "Casa & Utilidades", audience: "unissex", price: 30.00, production: "3-5 dias", colors: 8, badge: "", popular: 65, image: "bookmark-holder.jpg", icon: "fas fa-bookmark", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/650330-bookmark-holder", description: "Display para guardar e mostrar seus marcadores de página", tags: ["bookmark", "marcador", "livro", "display"] },
  { id: 63, name: "Porta-Retrato Desktop 25°", category: "Porta-Retratos", audience: "unissex", price: 18.00, production: "2-3 dias", colors: 10, badge: "", popular: 63, image: "desktop-frame-25.jpg", icon: "fas fa-image", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/1047649-desktop-picture-frame-stand-25deg", description: "Suporte para porta-retrato com ângulo de 25 graus", tags: ["porta-retrato", "foto", "mesa", "desktop"] },

  // Vasos & Plantas
  { id: 64, name: "Vaso Planter Clássico", category: "Vasos & Plantas", audience: "unissex", price: 30.00, production: "3-5 dias", colors: 12, badge: "", popular: 75, image: "planter-pot-vase.jpg", icon: "fas fa-leaf", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/models/46315-planter-pot-vase", description: "Vaso clássico para suculentas e plantas pequenas", tags: ["vaso", "planta", "suculenta", "jardim"] },

  // ============================================================
  // EXTRAS - Mais produtos para completar 120+
  // ============================================================

  // Meninas - Extras
  { id: 65, name: "Tulipa Perfeita com Vaso", category: "Flores & Decoração", audience: "meninas", price: 24.00, production: "3-5 dias", colors: 10, badge: "", popular: 74, image: "tulip-vase.jpg", icon: "fas fa-seedling", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/132900-tulip-flower-with-stem-stand-vases", description: "Tulipa com opções de vaso e suporte", tags: ["tulipa", "vaso", "decoração"] },
  { id: 66, name: "A Tulipa Gigante", category: "Flores & Decoração", audience: "meninas", price: 42.00, production: "5-7 dias", colors: 8, badge: "", popular: 70, image: "the-tulip.jpg", icon: "fas fa-seedling", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/928127-the-tulip", description: "Tulipa grande e detalhada, peça central de decoração", tags: ["tulipa", "grande", "decoração"] },
  { id: 67, name: "Porta-Joias Elegante", category: "Organização", audience: "meninas", price: 52.50, production: "5-7 dias", colors: 8, badge: "Personalizável", popular: 80, image: "jewelry-holder.jpg", icon: "fas fa-gem", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/jewelry%20holder%203d%20print%20model%20download", description: "Organizador de joias elegante com compartimentos", tags: ["joias", "organizador", "elegante", "acessórios"] },
  { id: 68, name: "Organizador de Maquiagem", category: "Organização", audience: "meninas", price: 60.00, production: "5-7 dias", colors: 10, badge: "", popular: 78, image: "makeup-organizer.jpg", icon: "fas fa-paint-brush", gradient: "gradient-5", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/makeup-organizer-3d-print-model-download", description: "Organizador para pincéis e itens de maquiagem", tags: ["maquiagem", "organizador", "pincéis", "beleza"] },
  { id: 69, name: "Mini Porta-Retrato Ajustável", category: "Porta-Retratos", audience: "meninas", price: 15.00, production: "2-3 dias", colors: 12, badge: "", popular: 62, image: "small-frame-stand.jpg", icon: "fas fa-image", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/models/462972-small-picture-frame-stand", description: "Mini suporte ajustável para fotos com parafusos impressos", tags: ["mini", "foto", "porta-retrato", "ajustável"] },
  { id: 70, name: "Suporte Porta-Retrato Fofo", category: "Porta-Retratos", audience: "meninas", price: 21.00, production: "2-3 dias", colors: 10, badge: "", popular: 68, image: "cute-frame-holder.jpg", icon: "fas fa-image", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/971986-picture-frame-stand-holder", description: "Suporte fofo e resistente para porta-retratos variados", tags: ["porta-retrato", "suporte", "fofo"] },

  // Meninos - Extras
  { id: 71, name: "Câmbio de Marchas Fidget", category: "Fidgets & Chaveiros", audience: "meninos", price: 24.00, production: "3-5 dias", colors: 10, badge: "Novo", popular: 88, image: "gear-shift-fidget.jpg", icon: "fas fa-cog", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/1548507-gear-shift-fidget-toy-v2-print-in-place", description: "Câmbio de marchas fidget, print-in-place V2", tags: ["fidget", "câmbio", "gear shift", "carro"] },
  { id: 72, name: "Bloco Fidget Chaveiro", category: "Fidgets & Chaveiros", audience: "meninos", price: 15.00, production: "2-3 dias", colors: 15, badge: "", popular: 76, image: "brick-fidget.jpg", icon: "fas fa-cube", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/models/2242060-brick-fidget-and-keychain-simple-clicky-cute", description: "Fidget formato bloco, simples e satisfatório de clicar", tags: ["fidget", "brick", "clicker", "bloco"] },
  { id: 73, name: "Fidget Gira-Polegar Click", category: "Fidgets & Chaveiros", audience: "meninos", price: 21.00, production: "3-5 dias", colors: 12, badge: "", popular: 82, image: "thumb-spin-fidget.jpg", icon: "fas fa-hand-pointer", gradient: "gradient-2", creator: "Eternity Labs", url: "https://makerworld.com/en/models/843772-click-click-thumb-spin-fidget", description: "Fidget de polegar que gira e clica", tags: ["fidget", "spin", "thumb", "clicker"] },
  { id: 74, name: "Dispositivo Caos Infinito", category: "Fidgets & Chaveiros", audience: "meninos", price: 33.00, production: "3-5 dias", colors: 8, badge: "Mais Vendido", popular: 89, image: "infinite-chaos.jpg", icon: "fas fa-infinity", gradient: "gradient-3", creator: "Eternity Labs", url: "https://makerworld.com/en/models/1457295-the-infinite-chaos-device-fidget", description: "Dispositivo de caos infinito, fidget hipnotizante", tags: ["fidget", "infinito", "caos", "premium"] },
  { id: 75, name: "Botão Rotativo Fidget", category: "Fidgets & Chaveiros", audience: "meninos", price: 18.00, production: "2-3 dias", colors: 12, badge: "", popular: 77, image: "knob-clicker.jpg", icon: "fas fa-circle-notch", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/models/1649123-knob-clicker-fidget-print-in-place", description: "Botão rotativo clicker, fidget giratório", tags: ["fidget", "knob", "clicker", "rotativo"] },
  { id: 76, name: "Engrenagem Click Chaveiro", category: "Fidgets & Chaveiros", audience: "meninos", price: 18.00, production: "2-3 dias", colors: 12, badge: "", popular: 74, image: "gearclick-keychain.jpg", icon: "fas fa-cog", gradient: "gradient-5", creator: "Lattaxil", url: "https://makerworld.com/en/models/1188910-gearclick-the-gear-keychain", description: "Chaveiro de engrenagem compacto e clicável", tags: ["chaveiro", "engrenagem", "gamer", "clicker"] },
  { id: 77, name: "Coração de Engrenagens Chaveiro", category: "Fidgets & Chaveiros", audience: "meninos", price: 21.00, production: "3-5 dias", colors: 10, badge: "", popular: 79, image: "gear-heart-fidget.jpg", icon: "fas fa-heart", gradient: "gradient-6", creator: "Spike_Mix", url: "https://makerworld.com/en/models/180647-gear-heart-fidget-toy-keychain", description: "Coração de engrenagens fidget toy como chaveiro", tags: ["coração", "engrenagem", "fidget", "chaveiro"] },

  // Unissex - Extras para Escritório
  { id: 78, name: "Organizador de Mesa Simples", category: "Organização", audience: "unissex", price: 37.50, production: "3-5 dias", colors: 12, badge: "", popular: 72, image: "simple-desk-organizer.jpg", icon: "fas fa-box", gradient: "gradient-7", creator: "3D Print Masters Hub", url: "https://makerworld.com/en/models/120659", description: "Organizador de mesa simples e escalável para escritório", tags: ["organizador", "mesa", "simples", "escritório"] },
  { id: 79, name: "Organizador de Mesa Multi-Compartimento", category: "Organização", audience: "unissex", price: 45.00, production: "3-5 dias", colors: 10, badge: "", popular: 70, image: "desk-organizer-stl.jpg", icon: "fas fa-boxes", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/1431054-desk-organizer-3d-print-stl", description: "Organizador de mesa com múltiplos compartimentos", tags: ["organizador", "mesa", "compartimentos"] },
  { id: 80, name: "Organizador de Mesa Premium", category: "Organização", audience: "unissex", price: 52.50, production: "5-7 dias", colors: 10, badge: "", popular: 68, image: "desk-organizer-premium.jpg", icon: "fas fa-box", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/models/1285826-desk-organizer", description: "Organizador de mesa premium design clean", tags: ["organizador", "mesa", "premium"] },
  { id: 81, name: "Pantera Negra Porta-Canetas", category: "Organização", audience: "unissex", price: 57.00, production: "5-7 dias", colors: 4, badge: "Novo", popular: 83, image: "black-panther-pen.jpg", icon: "fas fa-pen", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/2383866-black-panther-pen-holder-desk-organizer", description: "Porta-canetas Pantera Negra estilizado para mesa", tags: ["pantera negra", "porta-canetas", "herói", "desk"] },
  { id: 82, name: "Porta-Canetas para Monitor", category: "Organização", audience: "unissex", price: 22.50, production: "2-3 dias", colors: 10, badge: "", popular: 76, image: "under-monitor-pen.jpg", icon: "fas fa-pen", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/988411-under-monitor-pen-and-pencil-holder", description: "Porta-lápis compacto que fica embaixo do monitor", tags: ["caneta", "monitor", "compacto", "escritório"] },

  // Suportes Extras
  { id: 86, name: "Suporte Headphone Industrial", category: "Suportes & Setup", audience: "unissex", price: 57.00, production: "3-5 dias", colors: 6, badge: "", popular: 80, image: "headphone-industrial.jpg", icon: "fas fa-headphones", gradient: "gradient-7", creator: "Josh-3D", url: "https://makerworld.com/en/models/189326-headphone-stand-industrial", description: "Suporte headphone estilo industrial combinando com phone stand", tags: ["headphone", "industrial", "suporte"] },
  { id: 87, name: "Suporte Headphone + Celular Combo", category: "Suportes & Setup", audience: "unissex", price: 67.50, production: "5-7 dias", colors: 8, badge: "", popular: 79, image: "headphone-phone-stand.jpg", icon: "fas fa-headphones", gradient: "gradient-8", creator: "Alb37", url: "https://makerworld.com/en/models/475708-headphone-and-phone-stand", description: "Suporte combo para headphone e celular com gancho lateral", tags: ["headphone", "celular", "combo", "suporte"] },
  { id: 88, name: "Suporte Headphone Boneco", category: "Suportes & Setup", audience: "unissex", price: 48.00, production: "3-5 dias", colors: 10, badge: "", popular: 74, image: "minifigure-headphone.jpg", icon: "fas fa-headphones", gradient: "gradient-1", creator: "Thinkable", url: "https://makerworld.com/en/models/141033", description: "Suporte headphone em formato de minifigura divertida", tags: ["headphone", "minifigura", "divertido"] },

  // Meninas Extras - Mais fofinhos
  { id: 89, name: "Tulipa Desabrochando com Caule", category: "Flores & Decoração", audience: "meninas", price: 18.00, production: "2-3 dias", colors: 10, badge: "", popular: 71, image: "lovely-tulip.jpg", icon: "fas fa-seedling", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/138573-lovely-tulip-with-stem-blooming-perfection", description: "Tulipa desabrochando com perfeição, caule incluído", tags: ["tulipa", "flor", "desabrochando"] },

  // Meninos Extras - Mais ação
  { id: 90, name: "Controle N64 Fidget Chaveiro", category: "Gaming & Geek", audience: "meninos", price: 24.00, production: "3-5 dias", colors: 8, badge: "", popular: 75, image: "n64-fidget.jpg", icon: "fas fa-gamepad", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/563246-n64-fidget-keychain", description: "Fidget chaveiro formato controle N64 nostálgico", tags: ["N64", "fidget", "nintendo", "retro"] },
  { id: 91, name: "Estrela da Morte Giratória", category: "Gaming & Geek", audience: "meninos", price: 27.00, production: "3-5 dias", colors: 6, badge: "", popular: 80, image: "death-star-fidget.jpg", icon: "fas fa-moon", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/models/975108-turning-fidget-death-star-keychain", description: "Death Star giratória com mecanismo de catraca", tags: ["star wars", "death star", "fidget", "giratório"] },
  { id: 92, name: "Pistola Fidget Chaveiro", category: "Gaming & Geek", audience: "meninos", price: 18.00, production: "2-3 dias", colors: 10, badge: "", popular: 73, image: "pistol-fidget.jpg", icon: "fas fa-crosshairs", gradient: "gradient-5", creator: "MakerWorld", url: "https://makerworld.com/en/models/559347-fidget-standard-pistol-keychain-movable-slide", description: "Pistola fidget com slide móvel como chaveiro", tags: ["pistola", "fidget", "slide", "chaveiro"] },

  // Mais Organização
  { id: 93, name: "Organizador de Mesa Compacto", category: "Organização", audience: "unissex", price: 42.00, production: "3-5 dias", colors: 10, badge: "", popular: 71, image: "desk-organizer-3dprint.jpg", icon: "fas fa-box", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/models/1431054-desk-organizer-3d-print-stl", description: "Organizador para mesa de trabalho compacto", tags: ["organizador", "mesa", "trabalho"] },

  // Mais Meninas
  { id: 94, name: "Vaso Fofo para Suculentas", category: "Vasos & Plantas", audience: "meninas", price: 33.00, production: "3-5 dias", colors: 12, badge: "", popular: 73, image: "modern-succulent-pot.jpg", icon: "fas fa-leaf", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/models/843030-fluffy-planter-vase", description: "Vaso moderno para suculentas com textura fluffy", tags: ["vaso", "suculenta", "moderno", "fluffy"] },

  // Mais Gaming
  { id: 95, name: "Tecla de Teclado Fidget", category: "Gaming & Geek", audience: "meninos", price: 18.00, production: "2-3 dias", colors: 12, badge: "", popular: 72, image: "keycap-fidget.jpg", icon: "fas fa-keyboard", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/models/806892-keycap-fidget-keychain", description: "Tecla de teclado fidget como chaveiro", tags: ["keycap", "teclado", "fidget", "gamer"] },

  // Mais Armas/Fantasia
  { id: 96, name: "Esfera Clicker Fidget", category: "Fidgets & Chaveiros", audience: "unissex", price: 24.00, production: "3-5 dias", colors: 10, badge: "", popular: 76, image: "clicking-sphere.jpg", icon: "fas fa-circle", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/models/1971277-fidget-clicking-toy-sphere-keycaps", description: "Esfera fidget com teclas que clicam", tags: ["fidget", "esfera", "clicker", "keycap"] },

  // Mais Suportes
  { id: 97, name: "Suporte Celular Chaveiro Portátil", category: "Suportes & Setup", audience: "unissex", price: 15.00, production: "2-3 dias", colors: 15, badge: "", popular: 70, image: "keychain-phone-stand.jpg", icon: "fas fa-mobile-alt", gradient: "gradient-2", creator: "Infill 3D", url: "https://www.printables.com/model/749005-keychain-phone-stand", description: "Suporte de celular portátil como chaveiro", tags: ["celular", "suporte", "chaveiro", "portátil"] },

  // Mais Luminárias
  { id: 98, name: "Kit Porta-Copos com Caixa", category: "Casa & Utilidades", audience: "unissex", price: 37.50, production: "3-5 dias", colors: 8, badge: "", popular: 66, image: "makerworld-coaster.jpg", icon: "fas fa-glass-whiskey", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/models/115508-makerworld-coaster", description: "Set de 6 porta-copos com caixa organizadora", tags: ["coaster", "porta-copos", "set", "caixa"] },
  { id: 99, name: "Suporte Vertical Porta-Copos", category: "Casa & Utilidades", audience: "unissex", price: 21.00, production: "2-3 dias", colors: 10, badge: "", popular: 64, image: "coaster-holder-et3dp.jpg", icon: "fas fa-glass-whiskey", gradient: "gradient-4", creator: "ET3DP", url: "https://makerworld.com/en/models/727459", description: "Suporte vertical para porta-copos empilhados", tags: ["coaster", "suporte", "vertical"] },

  // Fidgets Print Template
  { id: 100, name: "Fidget Chaveiro Redesenhado V2", category: "Fidgets & Chaveiros", audience: "unissex", price: 18.00, production: "2-3 dias", colors: 15, badge: "", popular: 81, image: "fidget-template-v2.jpg", icon: "fas fa-hand-pointer", gradient: "gradient-5", creator: "We Be Printin'", url: "https://makerworld.com/en/models/821058-fidget-keychain-template-print-in-place-2", description: "Template fidget chaveiro V2 redesenhado e melhorado", tags: ["fidget", "template", "chaveiro", "print-in-place"] },

  // === MAIS PRODUTOS PARA ATINGIR 120+ ===

  // Meninas - Acessórios
  { id: 101, name: "Árvore Porta-Brincos", category: "Organização", audience: "meninas", price: 45.00, production: "5-7 dias", colors: 8, badge: "", popular: 77, image: "earring-tree.jpg", icon: "fas fa-gem", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/jewelry-display-3d-print-model-download", description: "Árvore para pendurar brincos e bijuterias", tags: ["brincos", "joias", "árvore", "display"] },
  { id: 102, name: "Organizador de Cosméticos", category: "Organização", audience: "meninas", price: 63.00, production: "5-7 dias", colors: 8, badge: "", popular: 74, image: "cosmetic-organizer.jpg", icon: "fas fa-paint-brush", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/cosmetic-3d-print-model-download", description: "Organizador multi-compartimento para cosméticos", tags: ["cosméticos", "organizador", "beleza"] },
  { id: 103, name: "Cone Porta-Anéis Decorativo", category: "Organização", audience: "meninas", price: 22.50, production: "2-3 dias", colors: 10, badge: "", popular: 68, image: "ring-holder.jpg", icon: "fas fa-ring", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/jewelry%20holder%203d%20print%20model%20download", description: "Cone decorativo para guardar anéis", tags: ["anéis", "porta-anéis", "decorativo"] },

  // Meninos - Extras Gaming
  { id: 104, name: "Suporte PS5 Cinnamoroll", category: "Gaming & Geek", audience: "meninos", price: 45.00, production: "5-7 dias", colors: 6, badge: "", popular: 76, image: "cinnamoroll-ps5.jpg", icon: "fas fa-gamepad", gradient: "gradient-1", creator: "UnchainedHobbies", url: "https://makerworld.com/en/models/585434-sanrio-cinnamoroll-ps5-controller-stand", description: "Suporte PS5 com busto Cinnamoroll fofo", tags: ["PS5", "controle", "cinnamoroll", "sanrio"] },
  { id: 105, name: "Suporte Controle Sob Mesa", category: "Suportes & Setup", audience: "meninos", price: 22.50, production: "2-3 dias", colors: 8, badge: "", popular: 73, image: "under-desk-controller.jpg", icon: "fas fa-gamepad", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/models/47866-under-desk-controller-holder", description: "Holder de controle sob a mesa com placas intercambiáveis", tags: ["controle", "mesa", "hidden", "gamer"] },

  // Unissex - Mais
  { id: 106, name: "Mini Fidget Deslizante", category: "Fidgets & Chaveiros", audience: "unissex", price: 18.00, production: "2-3 dias", colors: 10, badge: "", popular: 71, image: "g26-fidget.jpg", icon: "fas fa-hand-pointer", gradient: "gradient-3", creator: "MILITECH", url: "https://www.printables.com/model/1508863-g26-fidget-keychain-3d-printed-mini-slide-action-t", description: "Mini fidget slide-action compacto e satisfatório", tags: ["fidget", "slide", "mini", "compacto"] },
  { id: 107, name: "Fidget Chaveiro de Bolso", category: "Fidgets & Chaveiros", audience: "unissex", price: 15.00, production: "2-3 dias", colors: 12, badge: "", popular: 69, image: "fidget-maclab.jpg", icon: "fas fa-hand-pointer", gradient: "gradient-4", creator: "Mac-lab 3D", url: "https://www.printables.com/model/666012-fidget-keychain", description: "Fidget chaveiro design compacto para bolso", tags: ["fidget", "chaveiro", "compacto", "bolso"] },

  // Meninas - Presentes
  { id: 108, name: "Kit 3 Flores Presente", category: "Flores & Decoração", audience: "meninas", price: 67.50, production: "5-7 dias", colors: 10, badge: "Personalizável", popular: 86, image: "flower-kit-mix.jpg", icon: "fas fa-gift", gradient: "gradient-5", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/Flowers-3d-print-model-download", description: "Kit presente com 3 flores diferentes à sua escolha", tags: ["kit", "flores", "presente", "mix"] },
  { id: 109, name: "Porta-Retrato Coração Love", category: "Porta-Retratos", audience: "meninas", price: 33.00, production: "3-5 dias", colors: 8, badge: "", popular: 74, image: "love-heart-frame.jpg", icon: "fas fa-heart", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/collections/2709952-photo-picture-frame", description: "Porta-retrato formato coração para presente especial", tags: ["coração", "porta-retrato", "presente", "amor"] },

  // Meninos - Sci-fi
  { id: 110, name: "Paquímetro Fidget 5 em 1", category: "Fidgets & Chaveiros", audience: "meninos", price: 15.00, production: "2-3 dias", colors: 10, badge: "", popular: 73, image: "caliper-fidget.jpg", icon: "fas fa-ruler", gradient: "gradient-7", creator: "3D Prof", url: "https://www.printables.com/model/86502-caliper-catapult-fidget-toy-phone-stand-keychain-i", description: "5 em 1: paquímetro, catapulta, fidget, suporte e chaveiro", tags: ["multi", "fidget", "catapulta", "suporte", "chaveiro"] },

  // Unissex - Casa
  { id: 111, name: "Organizador Colmeia de Parede", category: "Casa & Utilidades", audience: "unissex", price: 42.00, production: "5-7 dias", colors: 8, badge: "", popular: 72, image: "honeycomb-wall.jpg", icon: "fas fa-hexagon-vertical-nft", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/wall-storage-honeycomb-3d-print-model-download", description: "Organizador de parede formato colmeia modular", tags: ["parede", "colmeia", "modular", "casa"] },

  // Mais Meninas fofos
  { id: 112, name: "Coelhinho Sorridente", category: "Animais Fofos", audience: "meninas", price: 21.00, production: "2-3 dias", colors: 12, badge: "", popular: 72, image: "smiley-bunny.jpg", icon: "fas fa-rabbit", gradient: "gradient-1", creator: "MakerWorld", url: "https://makerworld.com/en/collections/6603112-animal-figurine", description: "Coelhinho sorridente print-in-place", tags: ["coelho", "smiley", "fofo", "print-in-place"] },

  // Mais Meninos Gaming
  { id: 113, name: "Mjolnir Spinner do Thor", category: "Gaming & Geek", audience: "meninos", price: 27.00, production: "3-5 dias", colors: 6, badge: "", popular: 78, image: "thor-spinner.jpg", icon: "fas fa-bolt", gradient: "gradient-2", creator: "MakerWorld", url: "https://makerworld.com/en/collections/4467803-marvel-figure", description: "Spinner temático do Thor, Mjolnir giratório", tags: ["thor", "marvel", "spinner", "herói"] },
  { id: 114, name: "Diorama Batman Colecionável", category: "Gaming & Geek", audience: "meninos", price: 72.00, production: "7-10 dias", colors: 4, badge: "", popular: 80, image: "batman-diorama.jpg", icon: "fas fa-mask", gradient: "gradient-3", creator: "MakerWorld", url: "https://makerworld.com/en/collections/6589590-superhero", description: "Diorama do Batman para colecionadores", tags: ["batman", "diorama", "herói", "DC"] },
  { id: 115, name: "Mini Homem de Ferro Display", category: "Gaming & Geek", audience: "meninos", price: 42.00, production: "5-7 dias", colors: 6, badge: "", popular: 82, image: "mini-ironman.jpg", icon: "fas fa-user-astronaut", gradient: "gradient-4", creator: "MakerWorld", url: "https://makerworld.com/en/collections/4467803-marvel-figure", description: "Mini Iron Man com base de display", tags: ["iron man", "marvel", "mini", "display"] },

  // Mais Unissex
  { id: 116, name: "Suporte Universal para Tablet", category: "Suportes & Setup", audience: "unissex", price: 37.50, production: "3-5 dias", colors: 8, badge: "", popular: 74, image: "tablet-stand.jpg", icon: "fas fa-tablet", gradient: "gradient-5", creator: "MakerWorld", url: "https://makerworld.com/en/3d-models/404-office", description: "Suporte universal para tablets e iPads", tags: ["tablet", "iPad", "suporte", "universal"] },
  { id: 117, name: "Clips Organizador de Cabos (4un)", category: "Organização", audience: "unissex", price: 12.00, production: "1-2 dias", colors: 15, badge: "", popular: 80, image: "cable-clip-v2.jpg", icon: "fas fa-plug", gradient: "gradient-6", creator: "MakerWorld", url: "https://makerworld.com/en/more-models/3d-printed-cable-holder", description: "Clip organizador de cabos para mesa, set com 4", tags: ["cabo", "clip", "mesa", "organizador"] },
  { id: 118, name: "Kit Setup Gamer Completo", category: "Suportes & Setup", audience: "unissex", price: 165.00, production: "10-15 dias", colors: 6, badge: "Personalizável", popular: 88, image: "gamer-setup-kit.jpg", icon: "fas fa-desktop", gradient: "gradient-7", creator: "MakerWorld", url: "https://makerworld.com/en/3d-models/404-office", description: "Kit completo: suporte headphone + controle + celular + cabos", tags: ["kit", "gamer", "setup", "completo", "premium"] },
  { id: 119, name: "Vaso Geométrico Low Poly", category: "Vasos & Plantas", audience: "unissex", price: 30.00, production: "3-5 dias", colors: 12, badge: "", popular: 77, image: "low-poly-vase.jpg", icon: "fas fa-leaf", gradient: "gradient-8", creator: "MakerWorld", url: "https://makerworld.com/en/collections/705370-containers-planters-vases", description: "Vaso geométrico low poly para plantas pequenas", tags: ["vaso", "geométrico", "low poly", "planta"] },
  { id: 120, name: "Nome Personalizado 3D", category: "Personalizados", audience: "unissex", price: 33.00, production: "3-5 dias", colors: 15, badge: "Personalizável", popular: 90, image: "custom-name.jpg", icon: "fas fa-font", gradient: "gradient-1", creator: "Personalizado", url: "#", description: "Nome decorativo personalizado com sua escolha de fonte e cor", tags: ["nome", "personalizado", "decoração", "presente"] },
  { id: 121, name: "Logo Personalizada para Mesa", category: "Personalizados", audience: "unissex", price: 57.00, production: "5-7 dias", colors: 10, badge: "Personalizável", popular: 85, image: "custom-logo.jpg", icon: "fas fa-certificate", gradient: "gradient-2", creator: "Personalizado", url: "#", description: "Logo da sua empresa ou marca para mesa ou estante", tags: ["logo", "empresa", "personalizado", "corporativo"] },
  { id: 122, name: "Placa de Porta Personalizada", category: "Personalizados", audience: "unissex", price: 37.50, production: "3-5 dias", colors: 12, badge: "Personalizável", popular: 82, image: "custom-door-plate.jpg", icon: "fas fa-door-open", gradient: "gradient-3", creator: "Personalizado", url: "#", description: "Placa decorativa para porta com nome e desenho", tags: ["placa", "porta", "nome", "personalizado"] },
  { id: 123, name: "Brinde Corporativo com Logo", category: "Personalizados", audience: "unissex", price: 18.00, production: "3-5 dias", colors: 10, badge: "", popular: 78, image: "corporate-gift.jpg", icon: "fas fa-briefcase", gradient: "gradient-4", creator: "Personalizado", url: "#", description: "Brinde corporativo personalizado com logo, pedido mínimo 10 un", tags: ["brinde", "corporativo", "empresa", "logo"] },
  { id: 124, name: "Topo de Bolo Personalizado", category: "Personalizados", audience: "unissex", price: 45.00, production: "5-7 dias", colors: 8, badge: "Personalizável", popular: 86, image: "cake-topper.jpg", icon: "fas fa-birthday-cake", gradient: "gradient-5", creator: "Personalizado", url: "#", description: "Topo de bolo com nome, idade ou tema personalizado", tags: ["bolo", "topo", "aniversário", "personalizado", "festa"] },
];
